category/urls.py
from django.urls import path 
from .views import category_list 

app_name = 'category'

urlpatterns = [
    path('',category_list,name='category_list' ),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('category.urls',namespace = 'category')),
]

category/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    parent_category = models.CharField(("Parent Category"),max_length=50)
    sub_category_1  = models.CharField(("Sub Category 1"),max_length=50 ,blank=True,null=True)
    sub_category_2  = models.CharField(("Sub Category 2"),max_length=50 ,blank=True,null=True)

    def __str__(self):
        return self.parent_category
    
    class Meta:
        verbose_name_plural = 'Categories'

category/forms.py
# from django import forms
# from .models import Category

# class Category_Form(forms.Form):
#     active = forms.BooleanField()

#     class Meta:
#         model = Category    
        

category/views.py
from django.shortcuts import render , redirect
from .models import Category
from django.http import JsonResponse
from django.template.loader import render_to_string
# Create your views here.




def category_list(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        category_id = request.POST.get('category_id')
        category = Category.objects.get(id = category_id)
        category.sub_category_1 = f'SUB {category.parent_category} 1'
        category.sub_category_2 = f'SUB {category.parent_category} 2'
        
        Category.objects.create(parent_category=category.sub_category_1)
        Category.objects.create(parent_category=category.sub_category_2)

        # categories = Category.objects.all()
        # html = render_to_string('category/page.html',{'categories':categories,request:request})
        # return JsonResponse({'result':html})        

    return render(request,'category/page.html',{'categories':categories})

category/templates/category/page.html
<div id="refresh">
 <form method="post" id='category_form' action="{% url 'category:category_list' %}">
    {% csrf_token %}
    {% for category in categories %}
      <div class="form-check" id='categories_list'>  
          <input class="form-check-input" onchange="submit()" id='add_category' type="checkbox" value="{{category.id}}" name="category_id">
          <label class="form-check-label"  >{{category.parent_category}}</label>
      </div>
      {% endfor %}
  </form> 

</div>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  
  
  <script>
    $(document).ready(function(e){
      $(document).on('change','#category_form',function(e) {

      /*
      e.preventDefault(); 
      $.ajax({
        type: $(this).attr('method'),
        url : $(this).attr('action'),
        data: $(this).serialize(),
        dataType:'json',
        sucsses:function(response){
          console.log('add sub categories')
          $('#refresh').html(response['result'])

        },
        error:function(err){
          console.log(err)
        }
      }) 
*/
    });
      })
  </script> 
  

  